apiVersion: v1
kind: Service
metadata:
  name: udp-service
  namespace: default
spec:
  selector:
    app: udp-server
  type: ClusterIP
  ports:
    - name: udp-port
      port: 7778
      targetPort: 7778
      protocol: UDP